site_name: Blockchain Stuff
nav:
    - Home: index.md
    - Use Cases: usecases.md
    - Developing chaincode: developing.md
    - Deploying chaincoce: deploying.md
    - Architecture: architecture.md
theme: readthedocs
markdown_extensions:
  - admonition